CREATE DATABASE IF NOT EXISTS mormont;
USE mormont;
CREATE TABLE IF NOT EXISTS `users` (
  `username` VARCHAR(50)  NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`username`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;